### ISSUE TITLE
Error translating between RDF formats

### ISSUE THREAD

**Issue by NoelDeMartin** [solid/node-solid-server#1120]
## Please describe what you did in reproducible steps
- Added the url of my app (localhost:8080) to `trustedOrigins`
- Registered a user using `/api/accounts/new`
- Logged in from [my app](https://noeldemartin.github.io/solid-focus/) running on localhost.
- Created documents and containers -- worked as expected.
- Refreshed the page: got a "user not logged in" response from reading the root: `https://localhost:8443`.
- After looking at the network request, I noticed the header `Accept` was `*/*`, so I changed it to `text/turtle`. Now I get the following error: "Error translating between RDF formats"

## How did it work with 4.x series servers?
I got a turtle document with information of documents in my POD.

## What happened when you tried the same with the 5.0.0 beta?
I got the error "Error translating between RDF formats".

## Any material that will help, logs, error messages, etc.
Request headers:

```
GET / HTTP/1.1
Host: localhost:8443
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0
Accept: text/turtle
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: http://localhost:8080/
authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiIwMzhjYWYxZjI3OTdjZThiN2Q2NThjN2M1ZjU3ZmVkZSIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0Ojg0NDMiLCJleHAiOjE1NTE0NjUzNjksImlhdCI6MTU1MTQ2MTc2OSwiaWRfdG9rZW4iOiJleUpoYkdjaU9pSlNVekkxTmlJc0ltdHBaQ0k2SWxaVWVrcEthV2xNWkhKVkluMC5leUpwYzNNaU9pSm9kSFJ3Y3pvdkwyeHZZMkZzYUc5emREbzRORFF6SWl3aWMzVmlJam9pYUhSMGNITTZMeTlzYjJOaGJHaHZjM1E2T0RRME15OXdjbTltYVd4bEwyTmhjbVFqYldVaUxDSmhkV1FpT2lJd016aGpZV1l4WmpJM09UZGpaVGhpTjJRMk5UaGpOMk0xWmpVM1ptVmtaU0lzSW1WNGNDSTZNVFUxTWpVNU16Y3lNaXdpYVdGMElqb3hOVFV4TXpnME1USXlMQ0pxZEdraU9pSTNNems0WkdZeE1XRTJNV0ZoTkRreklpd2libTl1WTJVaU9pSTNSR2t5TFMxbmMxbFRWMDlaZFhCVGVEQllUVFJ0UVdodU1ESnpVRWRZTkhSS2FuTkhhRzFCYm1wWklpd2lZWHB3SWpvaU1ETTRZMkZtTVdZeU56azNZMlU0WWpka05qVTRZemRqTldZMU4yWmxaR1VpTENKamJtWWlPbnNpYW5kcklqcDdJbUZzWnlJNklsSlRNalUySWl3aVpTSTZJa0ZSUVVJaUxDSmxlSFFpT25SeWRXVXNJbXRsZVY5dmNITWlPbHNpZG1WeWFXWjVJbDBzSW10MGVTSTZJbEpUUVNJc0ltNGlPaUl3YW5wTFRYRTRRa1psZVhsaFltMXhVbmRpYUZCUmR6TkRVVUZqTkROb05WVlJTWEJSUm5GdVkwVlpXVXhCVlY5MldYbERYemxCUWpORWFFMWZiV3MyVjNGamVqWmxiMUJHV0hGSlJUbE5ObE5wVFROV1MzUXdXVGR6TmpaTVFtTnVTR0oxUlhReVNXMUdOMjVCZGw5SE5HRkVlREl5WjIxM05IZFFSMEZVY0dSaVZuRjRZbWxLZDNsV1puSk5kbmhNV2sxMVowNTVlVkp0ZUhkRk9VbzVOVVF3Ym1WNVpXOWlVelI1ZERscmFVVTJTMmRJTm1JMlRsWTJXakp4UW1WMVNFUklaRnBOYUZaaE5FdGtiVFpWUTBwMGRqQm9ObmhRYjJ4NmFGRnVjMUJTVEdZelJYWlNkM0kyTFVob1QydHhZVXhvU0c0eE5XSmZiazEyU2podVl6UnJWbFpHYW1SNVUyTmxkbUl6WTFnMGNHdzVNVEpGTkZGcVFWQkRhRW8zVFRGa2FWYzFUa3RhY1dveGQyOTZkRVZCVG5GTVJGbEZTbFpsUmxCc1YycEpjbUpsZUhwQ1NqZGpaWGRCT1hkdmFYRm9SM2NpZlgwc0ltRjBYMmhoYzJnaU9pSTBiSE5RVUZvM01IWXRSMHBIYlhsTFVrdG5PR0ZSSW4wLk5LcU5LOVJoTGp5VDBwaHUxdDZ5aldYNG1QNjBYRklRWFFfX2ZjMk1rQjljemtodEx0dGFxRGFJa0dIemlMc3hqTy0zT3hoX3gzelY2RVpocmpKQjRiRGRLdC0zRjFweDNTVV9VZG9aTnp0bXUwZFhCVTN6QXloUHdxcFJma01FcVRHamhiRWZLRjVPb1BxenoyOUxaRVE0LTVMRnZCekRpU1YybFVyY1NPUVY1bndMakpmclVQSHdvM2lUT3prRFVBTDQ3SXBLcWtnRXBNc3NaOFBGOWduX0JuaGJWcldPaFo5UVNBOUNERlM4akxpS1o5U3BBMDRWUm9MdWozYWFaRVM5RnF6YVdKc3dyYTUyRTBOWER6YTNUVzNmRTBvaW9RN3BSZmVoNlZwVF9meWx3RnR6LTRjSWEtNlNRZHduVXVKRElyaFhUSlczSWNJU1UzSDEzQSIsInRva2VuX3R5cGUiOiJwb3AifQ.FpeJGWE81Wy3P_VRLp4j0DibEHxhx26VGkG2-2kN7BYmLIaP53bKQbwkeV9XCuzWT-CGQu3Xy-Y8QdzqgXA4YUa3xvasF915l1QDk1Gt96GgiFop6mq35nUV_So3w1YCR_GPYVakBTb2KlQcWxn6aUrNtdR9VpJweS_S0zlMrwb-iuAEvKIPk_-U6JeJfMzUNIVELLh14nMdU12dN6v4w-5i_WFS3qIvec2aerM-Gei_6rDfihwyvxs-xCOS99OGPKQu0dH-WWKdlgDS81hgNO0XCfrjHUkjrRBWVl93C9Iz4djp7GNyeJVsh465qKbllKsn0bwZ_cyUE1kZyPECdw
Origin: http://localhost:8080
Connection: keep-alive
Cookie: connect.sid=s%3Ab_MHjLu1lIxjq8BcYSCfZk5jS54RgE9e.2T1U3b7eF8XQtnpywZ7XdE7%2BS8CBJ5iS2TdC6jkdeX0
Pragma: no-cache
Cache-Control: no-cache
```

Server logs:
```
  solid:ACL Using ACL https://localhost:8443/profile/.acl for ./card +9s
  solid:ACL accessDenied: checking access to <https://localhost:8443/profile/card> by <https://localhost:8443/profile/card#me> and origin <http://localhost:8080> +1ms
  solid:ACL    2  default authentications about <https://localhost:8443/profile/> in <https://localhost:8443/profile/.acl> +1ms
  solid:ACL Origin <http://localhost:8080> is trusted +1ms
  solid:ACL   modesAllowed: Origin null is trusted. +0ms
  solid:ACL    Checking auth <https://localhost:8443/profile/.acl#owner> with agent <https://localhost:8443/profile/card#me> +0ms
  solid:ACL     Agent explicitly authenticated. +1ms
  solid:ACL      Origin check not needed: no origin. +0ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Read> +0ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Write> +0ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Control> +0ms
  solid:ACL     Agent or group: Ok, its public. +0ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Read> +1ms
  solid:ACL accessDenied: modeURIorReasons: ["http://www.w3.org/ns/auth/acl#Read","http://www.w3.org/ns/auth/acl#Write","http://www.w3.org/ns/auth/acl#Control"] +0ms
  solid:ACL  checking <http://www.w3.org/ns/auth/acl#Read> +0ms
  solid:ACL   Mode required and allowed:<http://www.w3.org/ns/auth/acl#Read> +0ms
  solid:ACL Using ACL https://localhost:8443/profile/.acl for ./card +1ms
  solid:ACL Using ACL https://localhost:8443/profile/.acl for ./card +0ms
  solid:ACL Using ACL https://localhost:8443/profile/.acl for ./card +0ms
  solid:ACL Using ACL https://localhost:8443/profile/.acl for ./card +1ms
  solid:ACL Using ACL https://localhost:8443/profile/.acl for ./card +0ms
  solid:ACL Using ACL https://localhost:8443/profile/.acl for ./card +0ms
  solid:ACL Using ACL https://localhost:8443/profile/.acl for ./card +0ms
  solid:ACL accessDenied: checking access to <https://localhost:8443/profile/card> by null and origin <http://localhost:8080> +0ms
  solid:ACL    2  default authentications about <https://localhost:8443/profile/> in <https://localhost:8443/profile/.acl> +1ms
  solid:ACL Origin <http://localhost:8080> is trusted +0ms
  solid:ACL   modesAllowed: Origin null is trusted. +0ms
  solid:ACL    Checking auth <https://localhost:8443/profile/.acl#owner> with agent null +0ms
  solid:ACL     Agent or group: Fail: not public and not logged on. +0ms
  solid:ACL      The agent/group check fails +0ms
  solid:ACL       Check failed: User Unauthorized +0ms
  solid:ACL     Agent or group: Ok, its public. +1ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Read> +0ms
  solid:ACL accessDenied: modeURIorReasons: ["User Unauthorized","http://www.w3.org/ns/auth/acl#Read"] +0ms
  solid:ACL  checking <http://www.w3.org/ns/auth/acl#Read> +0ms
  solid:ACL   Mode required and allowed:<http://www.w3.org/ns/auth/acl#Read> +0ms
  solid:ACL accessDenied: checking access to <https://localhost:8443/profile/card> by null and origin <http://localhost:8080> +0ms
  solid:ACL    2  default authentications about <https://localhost:8443/profile/> in <https://localhost:8443/profile/.acl> +0ms
  solid:ACL Origin <http://localhost:8080> is trusted +1ms
  solid:ACL   modesAllowed: Origin null is trusted. +0ms
  solid:ACL    Checking auth <https://localhost:8443/profile/.acl#owner> with agent null +0ms
  solid:ACL     Agent or group: Fail: not public and not logged on. +0ms
  solid:ACL      The agent/group check fails +0ms
  solid:ACL       Check failed: User Unauthorized +0ms
  solid:ACL     Agent or group: Ok, its public. +0ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Read> +0ms
  solid:ACL accessDenied: modeURIorReasons: ["User Unauthorized","http://www.w3.org/ns/auth/acl#Read"] +0ms
  solid:ACL  checking <http://www.w3.org/ns/auth/acl#Write> +1ms
  solid:ACL   MODE REQUIRED NOT ALLOWED: <http://www.w3.org/ns/auth/acl#Write> Denying with User Unauthorized +0ms
  solid:ACL accessDenied: checking access to <https://localhost:8443/profile/card> by null and origin <http://localhost:8080> +0ms
  solid:ACL    2  default authentications about <https://localhost:8443/profile/> in <https://localhost:8443/profile/.acl> +0ms
  solid:ACL Origin <http://localhost:8080> is trusted +0ms
  solid:ACL   modesAllowed: Origin null is trusted. +0ms
  solid:ACL    Checking auth <https://localhost:8443/profile/.acl#owner> with agent null +1ms
  solid:ACL     Agent or group: Fail: not public and not logged on. +0ms
  solid:ACL      The agent/group check fails +0ms
  solid:ACL       Check failed: User Unauthorized +0ms
  solid:ACL     Agent or group: Ok, its public. +0ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Read> +0ms
  solid:ACL accessDenied: modeURIorReasons: ["User Unauthorized","http://www.w3.org/ns/auth/acl#Read"] +0ms
  solid:ACL  checking <http://www.w3.org/ns/auth/acl#Append> +0ms
  solid:ACL   MODE REQUIRED NOT ALLOWED: <http://www.w3.org/ns/auth/acl#Append> Denying with User Unauthorized +0ms
  solid:ACL accessDenied: checking access to <https://localhost:8443/profile/card> by null and origin <http://localhost:8080> +1ms
  solid:ACL    2  default authentications about <https://localhost:8443/profile/> in <https://localhost:8443/profile/.acl> +0ms
  solid:ACL Origin <http://localhost:8080> is trusted +0ms
  solid:ACL   modesAllowed: Origin null is trusted. +0ms
  solid:ACL    Checking auth <https://localhost:8443/profile/.acl#owner> with agent null +0ms
  solid:ACL     Agent or group: Fail: not public and not logged on. +0ms
  solid:ACL      The agent/group check fails +0ms
  solid:ACL       Check failed: User Unauthorized +0ms
  solid:ACL     Agent or group: Ok, its public. +1ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Read> +0ms
  solid:ACL accessDenied: modeURIorReasons: ["User Unauthorized","http://www.w3.org/ns/auth/acl#Read"] +0ms
  solid:ACL  checking <http://www.w3.org/ns/auth/acl#Control> +0ms
  solid:ACL   MODE REQUIRED NOT ALLOWED: <http://www.w3.org/ns/auth/acl#Control> Denying with User Unauthorized +0ms
  solid:ACL accessDenied: checking access to <https://localhost:8443/profile/card> by <https://localhost:8443/profile/card#me> and origin <http://localhost:8080> +0ms
  solid:ACL    2  default authentications about <https://localhost:8443/profile/> in <https://localhost:8443/profile/.acl> +0ms
  solid:ACL Origin <http://localhost:8080> is trusted +1ms
  solid:ACL   modesAllowed: Origin null is trusted. +0ms
  solid:ACL    Checking auth <https://localhost:8443/profile/.acl#owner> with agent <https://localhost:8443/profile/card#me> +0ms
  solid:ACL     Agent explicitly authenticated. +0ms
  solid:ACL      Origin check not needed: no origin. +0ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Read> +0ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Write> +1ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Control> +0ms
  solid:ACL     Agent or group: Ok, its public. +1ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Read> +1ms
  solid:ACL accessDenied: modeURIorReasons: ["http://www.w3.org/ns/auth/acl#Read","http://www.w3.org/ns/auth/acl#Write","http://www.w3.org/ns/auth/acl#Control"] +0ms
  solid:ACL  checking <http://www.w3.org/ns/auth/acl#Write> +0ms
  solid:ACL   Mode required and allowed:<http://www.w3.org/ns/auth/acl#Write> +0ms
  solid:ACL accessDenied: checking access to <https://localhost:8443/profile/card> by <https://localhost:8443/profile/card#me> and origin <http://localhost:8080> +0ms
  solid:ACL    2  default authentications about <https://localhost:8443/profile/> in <https://localhost:8443/profile/.acl> +0ms
  solid:ACL Origin <http://localhost:8080> is trusted +0ms
  solid:ACL   modesAllowed: Origin null is trusted. +0ms
  solid:ACL    Checking auth <https://localhost:8443/profile/.acl#owner> with agent <https://localhost:8443/profile/card#me> +1ms
  solid:ACL     Agent explicitly authenticated. +3ms
  solid:ACL      Origin check not needed: no origin. +0ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Read> +0ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Write> +0ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Control> +0ms
  solid:ACL     Agent or group: Ok, its public. +0ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Read> +0ms
  solid:ACL accessDenied: modeURIorReasons: ["http://www.w3.org/ns/auth/acl#Read","http://www.w3.org/ns/auth/acl#Write","http://www.w3.org/ns/auth/acl#Control"] +0ms
  solid:ACL  checking <http://www.w3.org/ns/auth/acl#Append> +0ms
  solid:ACL   Append required and Write allowed. OK +0ms
  solid:ACL accessDenied: checking access to <https://localhost:8443/profile/card> by <https://localhost:8443/profile/card#me> and origin <http://localhost:8080> +1ms
  solid:ACL    2  default authentications about <https://localhost:8443/profile/> in <https://localhost:8443/profile/.acl> +0ms
  solid:ACL Origin <http://localhost:8080> is trusted +0ms
  solid:ACL   modesAllowed: Origin null is trusted. +0ms
  solid:ACL    Checking auth <https://localhost:8443/profile/.acl#owner> with agent <https://localhost:8443/profile/card#me> +0ms
  solid:ACL     Agent explicitly authenticated. +0ms
  solid:ACL      Origin check not needed: no origin. +0ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Read> +0ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Write> +0ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Control> +0ms
  solid:ACL     Agent or group: Ok, its public. +1ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Read> +0ms
  solid:ACL accessDenied: modeURIorReasons: ["http://www.w3.org/ns/auth/acl#Read","http://www.w3.org/ns/auth/acl#Write","http://www.w3.org/ns/auth/acl#Control"] +0ms
  solid:ACL  checking <http://www.w3.org/ns/auth/acl#Control> +0ms
  solid:ACL   Mode required and allowed:<http://www.w3.org/ns/auth/acl#Control> +0ms
  solid:ACL Permissions on https://localhost:8443/profile/card for https://localhost:8443/profile/card#me: read write append control +0ms
  solid:ACL Permissions on https://localhost:8443/profile/card for public: read +0ms
  solid:get /profile/card on localhost +1ms
  solid:handlers GET -- Reading /home/noel/workspace/node-solid-server/data/profile/card$.ttl +2ms
  solid:accounts Account localhost is not available (for /) +425ms
  solid:ACL Using ACL https://localhost:8443/.acl for ./ +14ms
  solid:ACL accessDenied: checking access to <https://localhost:8443/> by <https://localhost:8443/profile/card#me> and origin <http://localhost:8080> +0ms
  solid:ACL    2 direct authentications about <https://localhost:8443/> +0ms
  solid:ACL Origin <http://localhost:8080> is trusted +0ms
  solid:ACL   modesAllowed: Origin null is trusted. +0ms
  solid:ACL     Agent or group: Ok, its public. +1ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Read> +0ms
  solid:ACL    Checking auth <https://localhost:8443/.acl#owner> with agent <https://localhost:8443/profile/card#me> +0ms
  solid:ACL     Agent explicitly authenticated. +0ms
  solid:ACL      Origin check not needed: no origin. +0ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Read> +0ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Write> +0ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Control> +0ms
  solid:ACL accessDenied: modeURIorReasons: ["http://www.w3.org/ns/auth/acl#Read","http://www.w3.org/ns/auth/acl#Write","http://www.w3.org/ns/auth/acl#Control"] +0ms
  solid:ACL  checking <http://www.w3.org/ns/auth/acl#Read> +0ms
  solid:ACL   Mode required and allowed:<http://www.w3.org/ns/auth/acl#Read> +0ms
  solid:ACL Using ACL https://localhost:8443/.acl for ./ +1ms
  solid:ACL Using ACL https://localhost:8443/.acl for ./ +0ms
  solid:ACL Using ACL https://localhost:8443/.acl for ./ +0ms
  solid:ACL Using ACL https://localhost:8443/.acl for ./ +0ms
  solid:ACL Using ACL https://localhost:8443/.acl for ./ +0ms
  solid:ACL Using ACL https://localhost:8443/.acl for ./ +0ms
  solid:ACL Using ACL https://localhost:8443/.acl for ./ +0ms
  solid:ACL accessDenied: checking access to <https://localhost:8443/> by null and origin <http://localhost:8080> +0ms
  solid:ACL    2 direct authentications about <https://localhost:8443/> +0ms
  solid:ACL Origin <http://localhost:8080> is trusted +1ms
  solid:ACL   modesAllowed: Origin null is trusted. +0ms
  solid:ACL     Agent or group: Ok, its public. +0ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Read> +0ms
  solid:ACL    Checking auth <https://localhost:8443/.acl#owner> with agent null +0ms
  solid:ACL     Agent or group: Fail: not public and not logged on. +0ms
  solid:ACL      The agent/group check fails +0ms
  solid:ACL       Check failed: User Unauthorized +0ms
  solid:ACL accessDenied: modeURIorReasons: ["http://www.w3.org/ns/auth/acl#Read","User Unauthorized"] +0ms
  solid:ACL  checking <http://www.w3.org/ns/auth/acl#Read> +0ms
  solid:ACL   Mode required and allowed:<http://www.w3.org/ns/auth/acl#Read> +0ms
  solid:ACL accessDenied: checking access to <https://localhost:8443/> by null and origin <http://localhost:8080> +0ms
  solid:ACL    2 direct authentications about <https://localhost:8443/> +0ms
  solid:ACL Origin <http://localhost:8080> is trusted +0ms
  solid:ACL   modesAllowed: Origin null is trusted. +0ms
  solid:ACL     Agent or group: Ok, its public. +1ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Read> +0ms
  solid:ACL    Checking auth <https://localhost:8443/.acl#owner> with agent null +0ms
  solid:ACL     Agent or group: Fail: not public and not logged on. +0ms
  solid:ACL      The agent/group check fails +0ms
  solid:ACL       Check failed: User Unauthorized +0ms
  solid:ACL accessDenied: modeURIorReasons: ["http://www.w3.org/ns/auth/acl#Read","User Unauthorized"] +0ms
  solid:ACL  checking <http://www.w3.org/ns/auth/acl#Write> +0ms
  solid:ACL   MODE REQUIRED NOT ALLOWED: <http://www.w3.org/ns/auth/acl#Write> Denying with All Required Access Modes Not Granted +0ms
  solid:ACL accessDenied: checking access to <https://localhost:8443/> by null and origin <http://localhost:8080> +0ms
  solid:ACL    2 direct authentications about <https://localhost:8443/> +0ms
  solid:ACL Origin <http://localhost:8080> is trusted +0ms
  solid:ACL   modesAllowed: Origin null is trusted. +0ms
  solid:ACL     Agent or group: Ok, its public. +0ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Read> +1ms
  solid:ACL    Checking auth <https://localhost:8443/.acl#owner> with agent null +0ms
  solid:ACL     Agent or group: Fail: not public and not logged on. +0ms
  solid:ACL      The agent/group check fails +0ms
  solid:ACL       Check failed: User Unauthorized +0ms
  solid:ACL accessDenied: modeURIorReasons: ["http://www.w3.org/ns/auth/acl#Read","User Unauthorized"] +0ms
  solid:ACL  checking <http://www.w3.org/ns/auth/acl#Append> +0ms
  solid:ACL   MODE REQUIRED NOT ALLOWED: <http://www.w3.org/ns/auth/acl#Append> Denying with All Required Access Modes Not Granted +0ms
  solid:ACL accessDenied: checking access to <https://localhost:8443/> by null and origin <http://localhost:8080> +0ms
  solid:ACL    2 direct authentications about <https://localhost:8443/> +0ms
  solid:ACL Origin <http://localhost:8080> is trusted +0ms
  solid:ACL   modesAllowed: Origin null is trusted. +0ms
  solid:ACL     Agent or group: Ok, its public. +0ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Read> +0ms
  solid:ACL    Checking auth <https://localhost:8443/.acl#owner> with agent null +0ms
  solid:ACL     Agent or group: Fail: not public and not logged on. +0ms
  solid:ACL      The agent/group check fails +1ms
  solid:ACL       Check failed: User Unauthorized +0ms
  solid:ACL accessDenied: modeURIorReasons: ["http://www.w3.org/ns/auth/acl#Read","User Unauthorized"] +0ms
  solid:ACL  checking <http://www.w3.org/ns/auth/acl#Control> +0ms
  solid:ACL   MODE REQUIRED NOT ALLOWED: <http://www.w3.org/ns/auth/acl#Control> Denying with All Required Access Modes Not Granted +0ms
  solid:ACL accessDenied: checking access to <https://localhost:8443/> by <https://localhost:8443/profile/card#me> and origin <http://localhost:8080> +0ms
  solid:ACL    2 direct authentications about <https://localhost:8443/> +0ms
  solid:ACL Origin <http://localhost:8080> is trusted +0ms
  solid:ACL   modesAllowed: Origin null is trusted. +0ms
  solid:ACL     Agent or group: Ok, its public. +0ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Read> +0ms
  solid:ACL    Checking auth <https://localhost:8443/.acl#owner> with agent <https://localhost:8443/profile/card#me> +0ms
  solid:ACL     Agent explicitly authenticated. +0ms
  solid:ACL      Origin check not needed: no origin. +0ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Read> +1ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Write> +0ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Control> +0ms
  solid:ACL accessDenied: modeURIorReasons: ["http://www.w3.org/ns/auth/acl#Read","http://www.w3.org/ns/auth/acl#Write","http://www.w3.org/ns/auth/acl#Control"] +0ms
  solid:ACL  checking <http://www.w3.org/ns/auth/acl#Write> +0ms
  solid:ACL   Mode required and allowed:<http://www.w3.org/ns/auth/acl#Write> +0ms
  solid:ACL accessDenied: checking access to <https://localhost:8443/> by <https://localhost:8443/profile/card#me> and origin <http://localhost:8080> +0ms
  solid:ACL    2 direct authentications about <https://localhost:8443/> +0ms
  solid:ACL Origin <http://localhost:8080> is trusted +0ms
  solid:ACL   modesAllowed: Origin null is trusted. +0ms
  solid:ACL     Agent or group: Ok, its public. +0ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Read> +0ms
  solid:ACL    Checking auth <https://localhost:8443/.acl#owner> with agent <https://localhost:8443/profile/card#me> +0ms
  solid:ACL     Agent explicitly authenticated. +1ms
  solid:ACL      Origin check not needed: no origin. +0ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Read> +0ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Write> +0ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Control> +0ms
  solid:ACL accessDenied: modeURIorReasons: ["http://www.w3.org/ns/auth/acl#Read","http://www.w3.org/ns/auth/acl#Write","http://www.w3.org/ns/auth/acl#Control"] +0ms
  solid:ACL  checking <http://www.w3.org/ns/auth/acl#Append> +0ms
  solid:ACL   Append required and Write allowed. OK +0ms
  solid:ACL accessDenied: checking access to <https://localhost:8443/> by <https://localhost:8443/profile/card#me> and origin <http://localhost:8080> +0ms
  solid:ACL    2 direct authentications about <https://localhost:8443/> +0ms
  solid:ACL Origin <http://localhost:8080> is trusted +0ms
  solid:ACL   modesAllowed: Origin null is trusted. +0ms
  solid:ACL     Agent or group: Ok, its public. +0ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Read> +0ms
  solid:ACL    Checking auth <https://localhost:8443/.acl#owner> with agent <https://localhost:8443/profile/card#me> +1ms
  solid:ACL     Agent explicitly authenticated. +0ms
  solid:ACL      Origin check not needed: no origin. +0ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Read> +0ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Write> +0ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Control> +0ms
  solid:ACL accessDenied: modeURIorReasons: ["http://www.w3.org/ns/auth/acl#Read","http://www.w3.org/ns/auth/acl#Write","http://www.w3.org/ns/auth/acl#Control"] +0ms
  solid:ACL  checking <http://www.w3.org/ns/auth/acl#Control> +0ms
  solid:ACL   Mode required and allowed:<http://www.w3.org/ns/auth/acl#Control> +0ms
  solid:ACL Permissions on https://localhost:8443/ for https://localhost:8443/profile/card#me: read write append control +0ms
  solid:ACL Permissions on https://localhost:8443/ for public: read +0ms
  solid:get / on localhost +0ms
  solid:handlers GET -- Reading /home/noel/workspace/node-solid-server/data/index.html +1ms
[xmldom error]	entity not found:&ndash; 
@#[line:8,col:3]
[xmldom error]	entity not found:&ndash; 
@#[line:17,col:27]
  solid:get error translating: / text/html -> text/turtle -- 500 RDFaProcessor.trim is not a function +20ms
  solid:server Error page because of: { [HTTPError: Error translating between RDF formats]
  name: 'HTTPError',
  message: 'Error translating between RDF formats',
  status: 500 } +0ms
```

**Comment by kjetilk** [comment]
Thanks a lot for the thorough report. Looks like a regression bug to me indeed. We'll have a good look at it.

**Comment by megoth** [comment]
@NoelDeMartin could you provide the resource that you were trying to translate to Turtle?

**Comment by NoelDeMartin** [comment]
@megoth This happens when I do a GET on the root `https://localhost:8443`, looking at the logs seems like it's trying to translate `data/index.html` to turtle and that's where it fails. I am reading from that url because the request at `https://localhost:8443/profile/card#me` returns this: `pim:storage </> ;`.

**Comment by megoth** [comment]
That sounds like a maybe `LDP.get` needs a bit of tweaking. I've put this on the [NSS -5.0.0 project board](https://github.com/orgs/solid/projects/1#card-18398113) to give this a higher priority. Hopefully have time today or tomorrow to give this a go.

**Comment by jaxoncreed** [comment]
Hi @NoelDeMartin ,

I think the server is working as intended. There is no RDF resource at https://localhost:8443. You can get a resource from https://localhost:8443/SOME_PATH (example https://localhost:8443/profile)

**Comment by NoelDeMartin** [comment]
@jaxoncreed I am trying to get an RDF resource because I get `pim:storage </> ;` from the profile, how else am I supposed to query it? In v4.X I did it like this, without specifying text/turtle content type, but that's the format I got in the response.

**Comment by jaxoncreed** [comment]
@NoelDeMartin My bad. I'll get on to correcting this as soon as I can.

**Comment by megoth** [comment]
I suspect that requestedType.includes('text/html') in https://github.com/solid/node-solid-server/blob/master/lib/handlers/get.js#L81 is a bit to eager: it will try to fetch HTML irrespective of whether you're asking for a TTL-response. And then NSS tries to convert the fetched HTML representation to TTL.

**Comment by jaxoncreed** [comment]
Fixed in #1156. Content type was not being properly passed to the ldp

**Comment by Otto-AA** [comment]
Sorry for commenting on a closed issue, but my problem seems connected to this.

For a file manager I would like to fetch the contents of the "root" directory. In the old version it worked with sending a request to the "root path" (e.g. https://otman.solid.community/), but as mentioned in this issue, the 5.0.0 version doesn't return a turtle file. I didn't find out yet how to do this with the new version, so I would be very glad if you can point me into the right direction. (I guess I'm just missing something of the way solid handles this and actually don't think it's a bug)

Here is a bit more context if needed: https://github.com/Otto-AA/solid-filemanager/issues/24

**Comment by NoelDeMartin** [comment]
@Otto-AA Are you explicitly setting the `Accept` header to `text/turtle` in the request? In the previous version it wasn't necessary, but I believe in this version I had to do it or it wouldn't work.

**Comment by Otto-AA** [comment]
If I explicitly set the Accept header to `text/turtle`, I get a 500 response with the `Error translating between RDF formats`. If I don't set it, I get it as html.

Here's a screenshot of it:
![image](https://user-images.githubusercontent.com/21040751/55708292-d9ebc180-59e5-11e9-8bb0-3f8d9a34d82a.png)

**Comment by NoelDeMartin** [comment]
@Otto-AA Yes, that error is what's been fixed in this issue. Keep in mind that it's been fixed on the branch `master`, if you're using the branch `release/v5.0.0` this fix is not included.

**Comment by Otto-AA** [comment]
@NoelDeMartin Ok, thanks. I don't have the resources to test it with the new server version, but I guess that this will fix it. Thanks for the clarification :+1:

**Comment by Leoudayan** [comment]
@NoelDeMartin Is it possible for you to explain how to merge the branch master with the existing 5.0.0 version?I tried to follow the instructions to merge the master with the 5.0.0 release (https://github.com/solid/node-solid-server/blob/master/.travis.yml ) But getting error - no such file or directory, /../../package.json when i tried npm ci.

**Comment by michielbdejong** [comment]
Looks like this error is back (see also comment earlier "it is not working in 5.0"?)

Very easy to reproduce:

```sh
curl -i -H 'Accept: text/turtle' https://michielbdejong.inrupt.net/
HTTP/1.1 500 Internal Server Error
X-Powered-By: solid-server/5.1.4
Vary: Accept, Authorization, Origin
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: Authorization, User, Location, Link, Vary, Last-Modified, ETag, Accept-Patch, Accept-Post, Updates-Via, Allow, WAC-Allow, Content-Length, WWW-Authenticate
Allow: OPTIONS, HEAD, GET, PATCH, POST, PUT, DELETE
Link: <.acl>; rel="acl", <.meta>; rel="describedBy", <http://www.w3.org/ns/ldp#Resource>; rel="type"
WAC-Allow: user="read",public="read"
MS-Author-Via: SPARQL
Updates-Via: wss://michielbdejong.inrupt.net
Content-Type: text/plain; charset=utf-8
Content-Length: 38
ETag: W/"26-QBI7EYtDt6zJzGYxyvtGCQrnW5Q"
Date: Wed, 12 Jun 2019 10:29:32 GMT
Connection: keep-alive

Error translating between RDF formats

**Comment by jaxoncreed** [comment]
Well, that's saddening. Will triage

**Comment by michielbdejong** [comment]
This happens on inrupt.net as well as on dev.inrupt.net.

**Comment by ludwigschubi** [comment]
I don't exactly know how the solid community pods are updated/maintained, but since this affects everyone that is developing with their community pods, would it be possible for the maintainers to downgrade to a more stable version for now?

**Comment by jaxoncreed** [comment]
Should be solved in https://github.com/solid/node-solid-server/pull/1292
